Updated gerritrc

diff --git a/system-files/gerritrc b/system-files/gerritrc
--- a/system-files/gerritrc
+++ b/system-files/gerritrc
@@ -10,42 +10,43 @@ function list_contains() {
     fi
     return $result
 }
- 
-#export GERRITUSER=<username>
-#export GERRITSRVR=<server>
-#export GERRITPORT=<port>
- 
+
+export GERRITUSER=kevinkredit
+export GERRITSRVR=gerritcodereview
+export GERRITPORT=29418
+export GERRITWEBPORT=8080
+
 alias gerrit_shell="ssh $GERRITUSER@$GERRITSRVR"
- 
+
 function gerrit_ssh (){
     ssh -p $GERRITPORT $GERRITUSER@$GERRITSRVR $*
 }
- 
+
 function gerrit_ssh_cmd (){
     gerrit_ssh gerrit $*
 }
- 
+
 function git_current_change_id (){
     git show -s | grep -Po '(?<=Change-Id: ).+'
 }
- 
+
 function gerrit_query_current (){
     gerrit_ssh_cmd query $(git_current_change_id)
 }
- 
+
 function gerrit_current_project (){
     gerrit_query_current | grep -Po '(?<=project: ).+'
 }
- 
+
 function gerrit_ls_groups () {
     gerrit_ssh_cmd ls-groups
 }
- 
+
 function gerrit_set_review_group (){
     local group=$1
     local current_project=$(gerrit_current_project)
     local gerrit_groups=$(gerrit_ls_groups)
- 
+
     if $(list_contains $group "$gerrit_groups"); then
         echo "Setting $group to review $current_project"
         gerrit_ssh_cmd set-reviewers --project $current_project --add $group $(git_current_change_id)
@@ -58,16 +59,50 @@ function gerrit_set_review_group (){
         done
     fi
 }
- 
+
 function gerrit_get_commit_hooks(){
-    if [ ! -d ".git" ]; then
-        echo "Change to directory with \".git\""
-        return 1
-    fi
-    scp -p  -P $GERRITPORT $GERRITUSER@$GERRITSRVR:hooks/commit-msg .git/hooks/commit-msg
+    GIT_TOP=$(git rev-parse --show-toplevel)
+    scp -p -P $GERRITPORT $GERRITUSER@$GERRITSRVR:hooks/commit-msg $GIT_TOP/.git/hooks/commit-msg
     if [ $? -eq 0 ]; then
-        echo "Sucessfully downlaoded gerrit commit message hook"
+        echo "Successfully downloaded gerrit commit message hook"
     else
         echo "Error downloading gerrit commit message hook"
     fi
+}
+
+function gerrit_rm_commit_hook() {
+    GIT_TOP=$(git rev-parse --show-toplevel)
+    rm -f $GIT_TOP/.git/hooks/commit-msg
+    echo "Deleted gerrit commit message hook"
+}
+
+function gerrit_setup() {
+    if [[ $# != 1 ]]; then
+        echo "Error: enter the Gerrit server project path"
+        return 1
+    fi
+    gerrit_get_commit_hooks
+    git remote add gerrit http://$GERRITSRVR:$GERRITWEBPORT/$1
+    if [[ $? != 0 ]]; then
+        echo "Error adding gerrit remote"
+        return 1
+    else
+        echo "Successfully added gerrit remote"
+    fi
+    git fetch gerrit
+}
+
+function gerrit_teardown() {
+    gerrit_rm_commit_hook
+    git remote remove gerrit
+    echo "Removed gerrit remote"
+}
+
+function gpush() {
+    if [[ $# != 4 ]]; then
+        echo "Error: enter 'gpush COMMIT BRANCH TOPIC GROUP"
+        return 1
+    fi
+    git push gerrit $1:refs/for/$2%topic=$3
+    gerrit_set_review_group $4
 }
